name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  unit-tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Wizard tests
            task: :plugin-wizard:test
          - name: Route model + collectors fast tests
            task: :plugin-route-collectors:fastTest
          - name: Route spring fast tests
            task: :plugin-route-spring:fastTest
          - name: Route protocol fast tests
            task: :plugin-route-protocol:fastTest
          - name: Route analysis fast tests
            task: :plugin-route-analysis:fastTest
          - name: Route collectors platform tests
            task: :plugin-route-collectors:test
          - name: Route spring platform tests
            task: :plugin-route-spring:test
          - name: Route protocol platform tests
            task: :plugin-route-protocol:test
          - name: Route analysis platform tests
            task: :plugin-route-analysis:test
          - name: Plugin client tests
            task: :plugin:test

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: 25
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - run: ./gradlew ${{ matrix.task }}

  build:
    name: Build
    needs: unit-tests
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 25 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - run: ./gradlew build -x test
