name: "Publish Artifacts"

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java for Publishing
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_publishVersion: ${{ github.ref }}
          ORG_GRADLE_PROJECT_gitHubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_gitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        run: |
          RELEASE_NAME=`echo ${{ github.ref }} | sed -e 's/refs\/tags\///'`
          VERSION=`echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//'`
          ARTIFACT_NAME=${{ github.event.repository.name }}-$VERSION.zip
          curl -s -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --upload-file build/distributions/$ARTIFACT_NAME \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_NAME/assets?name=$ARTIFACT_NAME"
